# Generated by Django 4.2.7 on 2023-11-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=150, verbose_name="Ваш логин")),
                (
                    "password",
                    models.TextField(max_length=150, verbose_name="Ваш пороль"),
                ),
                (
                    "nickname",
                    models.TextField(max_length=150, verbose_name="Отображаемое имя"),
                ),
            ],
        ),
    ]
