# Generated by Django 4.2.7 on 2023-11-18 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        max_length=150, verbose_name="Название музыкального файла"
                    ),
                ),
                (
                    "mfile",
                    models.FileField(
                        max_length=150, upload_to="", verbose_name="Музыкальный файл"
                    ),
                ),
                (
                    "loader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="musics.user",
                    ),
                ),
            ],
        ),
    ]
