# Generated by Django 4.2.7 on 2023-11-27 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("musics", "0002_musicfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="musicfile",
            name="loader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="musicfile",
            name="mfile",
            field=models.FileField(
                max_length=150, upload_to="musics", verbose_name="Музыкальный файл"
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="favorite",
            name="music",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favoritemusic",
                to="musics.musicfile",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favoriteuser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
