# Generated by Django 4.2.7 on 2023-11-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0003_favorite_alter_musicfile_loader_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="musicfile",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="musicfile",
            name="mfile",
            field=models.FileField(
                max_length=150, upload_to="", verbose_name="Музыкальный файл"
            ),
        ),
    ]
