# Generated by Django 4.2.7 on 2023-11-29 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0005_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="music",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favoritemusic",
                to="musics.musicfile",
            ),
        ),
    ]
