# Generated by Django 4.2.7 on 2023-12-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0007_song_loader_alter_favorite_music_delete_musicfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="audio_link",
        ),
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=models.FileField(null=True, upload_to="audio"),
        ),
        migrations.AlterField(
            model_name="song",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="img"
            ),
        ),
    ]
