# Generated by Django 4.2.7 on 2023-12-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0008_remove_song_audio_link_alter_song_audio_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="song",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
